### ISSUE TITLE
Need to be able to deploy applications

### ISSUE THREAD

**Issue by cpitman** [cpitman/puppet-jboss_admin#3]
A user needs to be able to manage the deployments within a container. This may require a new plumbing type, additional analysis is needed.

**Comment by itewk** [comment]
@cpitman should I find a way to share with you what I am doing? Though it is now more complicated because I am deploying "Bundles" which I am parsing and then deploying the correct artifacts from the bundle of multiple layers/cluster of an application and the property files and such.

**Comment by danmikita** [comment]
@itewk Do you have an example of what the $cli_path is for the deployment resource?

**Comment by itewk** [comment]
@danmikita I have an example here you can use for deploying an artifact, https://github.com/itewk/puppet-jboss_eap_server/blob/master/manifests/artifact.pp

Give that a look and see if it solves your problem. If not let me know.

**Comment by danmikita** [comment]
@itewk Thank you! This is very helpful.

**Comment by itewk** [comment]
@danmikita glad to help. Let me know if you have any other questions or issues.
