### ISSUE TITLE
Add jboss_batch type

### ISSUE THREAD

**Issue by itewk** [cpitman/puppet-jboss_admin#32]
There are some resources that have to be added in batch

case in point modcluster.

see https://issues.jboss.org/browse/JBPAPP6-1420 for more details.

This means we need some mechanism to specify resources in batch or else force users to just jboss_exec in these cases.

-----------

jboss_batch type will have an array 'batch' attribute that has an ordered list of batch commands and resources.

**Comment by cpitman** [comment]
Merged
