### ISSUE TITLE
Can not generate documenation due to duplicate types in cutome_resources

### ISSUE THREAD

**Issue by itewk** [cpitman/puppet-jboss_admin#45]
Can the resource types defined in manifests/internal/custom_resources be moved outside of the manifests directory?

The problem is the puppet script that is being used to try and generate documentation for all of the modules at the customer is chocking on having the same type defined twice in two different locations. This will happen to anyone who tries to generate puppet docs.

Error: Could not generate documentation: Definition 'jboss_admin::resource:rotocol' is already defined at /home/nfs-home/woverholt/puppet/doc/OCIO-PUPPET/modules/jboss_admin/manifests/internal/custom_resource/protocol.pp:14; cannot be redefined at /home/nfs-home/woverholt/puppet/doc/OCIO-PUPPET/modules/jboss_admin/manifests/resource/protocol.pp:14

**Comment by cpitman** [comment]
No, that is certainly possible, and probably a good idea anyways.
