### ISSUE TITLE
syntax errors reported by Puppet 3.3

### ISSUE THREAD

**Issue by itewk** [cpitman/puppet-jboss_admin#46]
These errors may only be being reported by my environment due to being on Puppet 3.3 but not sure.

     14 Error while parsing /etc/puppet/environments/PSB/modules/jboss_admin/manifests/resource/json_formatter.pp: Syntax error at '.' at line 18
     14 Error while parsing /etc/puppet/environments/PSB/modules/jboss_admin/manifests/resource/thread_factory.pp: Syntax error at '%' at line 18

**Comment by cpitman** [comment]
I believe this issue is replaced by #50 ?
