### ISSUE TITLE
jboss_admin::resource::property can have none strings as their values and thus the default validation to enforce a string value must be removed. 

### ISSUE THREAD

**Issue by itewk** [cpitman/puppet-jboss_admin#48]
jboss_admin::resource::property can have none strings as their values and thus the default validation to enforce a string value must be removed.

**Comment by cpitman** [comment]
Interesting, there are some properties that are nillable and some that are not. The generator does not take that into account when deciding that two "property" types are the same.

**Comment by itewk** [comment]
@cpitman #cuzjbosscli
