### ISSUE TITLE
when using jboss_admin::resource::* no way to undef attribute

### ISSUE THREAD

**Issue by itewk** [cpitman/puppet-jboss_admin#57]
Currently all jboss_admin::resource::*s run a delete_undef_values on all the provided options. The problem with this is that it means there is no way when using a resource to unset an attribute value.

I understand the original reason for this 'delete_undef_values' was so that defaults would not be overwritten if not specified, but that comes at the cost of never being able to unset attributes.

@cpitman  thoughts on this one?

**Comment by cpitman** [comment]
Setting an attribute to `undefined` is a special value that will clear out any existing attribute value. `undef`, as you've seen, is used to mean the value is unspecified.

**Comment by itewk** [comment]
@cpitman what about for an array value? The validation says that "undefined" is not an array. I would assume the same holds true for booleans and such.

**Comment by cpitman** [comment]
Oops, good point, those are not working together. Should be easy to fix.

**Comment by itewk** [comment]
This did not seem to catch all resources, jboss_admin::resource::subsystem_ee for example, which is the one I am having trouble with :)
