### ISSUE TITLE
jboss_admin::module should use ensure_resource rather then exec

### ISSUE THREAD

**Issue by itewk** [cpitman/puppet-jboss_admin#59]
For creating the parent directories of modules the Puppet stdlib ensure_resource should be used rather then exec so that Puppet knows those folders are under its control. This is important when managing the parent modules directory to import other modules which then could purge jboss_admin::modules if file resources are not being used.

**Comment by jairojunior** [comment]
@itewk @cpitman Sorry to post here but i couldn't find another way to contact you guys.

It seems like we are working in something very close: 

* https://github.com/jairojunior/wildfly-cli-wrapper
* https://github.com/jairojunior/biemond-wildfly

I was working with the code above for an internal project (JBoss EAP) and decided to open source this to improve forge wildfly module.

I'm really interested in this project and maybe I'll be able to help. Will take a look at your code base tomorrow and hope you can contact me at junior.jairo1 [at] gmail . com

**Comment by cpitman** [comment]
Merged in!
