### ISSUE TITLE
version tagging?

### ISSUE THREAD

**Issue by itewk** [cpitman/puppet-jboss_admin#65]
@cpitman what do you think about starting to tag versions? It would make it easier to consume if I could specify which version tag I am currently running rather then a hash. Not sure how we would decide when to cut a new version, other then Ian saying, hey, I need a new version. Thoughts?

**Comment by jairojunior** [comment]
@itewk Puppet Approved Criteria (https://forge.puppetlabs.com/approved/criteria) recommends SemVer (http://semver.org/spec/v1.0.0.html)

* A normal version number MUST take the form X.Y.Z where X, Y, and Z are integers. X is the major version, Y is the minor version, and Z is the patch version. Each element MUST increase numerically by increments of one. For instance: 1.9.0 -> 1.10.0 -> 1.11.0.

* Patch version Z (x.y.Z | x > 0) MUST be incremented if only backwards compatible bug fixes are introduced. A bug fix is defined as an internal change that fixes incorrect behavior.

* Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API. It MAY be incremented if substantial new functionality or improvements are introduced within the private code. It MAY include patch level changes. Patch version MUST be reset to 0 when minor version is incremented.

* Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API. It MAY include minor and patch level changes. Patch and minor version MUST be reset to 0 when major version is incremented.

**Comment by itewk** [comment]
@jairojunior My thoughts exactly :)

@cpitman thoughts?

**Comment by cpitman** [comment]
Ok guys, new drop on puppet forge (1.0.1) and a new tag to go with it (release-1.0.1)
