### ISSUE TITLE
add ability to disable restart/cleanup

### ISSUE THREAD

**Issue by itewk** [cpitman/puppet-jboss_admin#66]
I need a way to disable the automatic restart of JBoss EAP.

The use case is I need to be able to roll out changes to the puppet configuration to an entire environment, even if that configuration requires a restart, with out the restart being forced.

Concreate example:

updating to configure RBAC. I want to roll this out to the entire infrastrcture, but when the puppet code updates the next puppet run will update all the jboss servers, and then they will restart based on that change. that is a minor annoyance in the lab, but a problem in production where jboss can not just restart willy nilly.

I need more fine grained control over when puppet is allowed to restart jboss.

@cpitman any ideas?

**Comment by cpitman** [comment]
Merged! Thanks for the contribution.

**Comment by itewk** [comment]
@cpitman thank you!
