### ISSUE TITLE
can't convert nil into Array when noop enabled for jboss_batch

### ISSUE THREAD

**Issue by itewk** [cpitman/puppet-jboss_admin#82]
There is a bug with the fix for issue #73 for jboss_batch resources. The following error is thrown if noop is enabled for the jboss_batch resource:

Error: /Stage[main]/....................../Jboss_batch[Local Authentication: Pre JBoss EAP 6.3.0]: Could not evaluate: can't convert nil into Array

This is because there is not a null check for the "is" parameter of the "insync?" function.

**Comment by ramius345** [comment]
I have done a peer review of this change and it looks good to me.  The added if statement will catch the case where the _is_ is nil.  The rest of the code is unchanged from the previous implementation and appears to be correct to the best of my knowledge.

**Comment by itewk** [comment]
@ramius345 thank you!

**Comment by itewk** [comment]
merged
